Update issue templates
axonivy-market/demo-projects pull request #555
Opened 2024-05-15 12:03 UTC by ivy-sgi

2024-05-17 11:34 UTC, phochstr requested changes
Even though this is open source, it is using Ivy. So, we have to gather as much information as possible so we or others can analyze what happens. Logs and thread dumps are the first two that come to my mind, but there are certainly others.

Therefore, I'd opt for a link to a checklist and procedures library.

2024-05-17 11:34 UTC, phochstr commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Add any other context about the problem here.
I'd add add here:

- if you get error messages, please include the ivy logs showing these errors.
- if you experience a stuck application, please create several thread dumps.

Can we create a page containing a checklist what to include and procedures, like for instance creating thread dumps with jstack etc. ?

2024-06-07 09:58 UTC, alexsuter commented
I'll close the PR and prefix the branch with stale/*. So that there are no builds running on our Jenkins server.

If you want to continue the work you can create a PR out of the stale/* branch.

The demo-projects is a special Axon Ivy Market artifact which can only be successfully built on our Jenkins server (because of test infrastructure which is only available in our internal network). For each branch builds are running unless they are prefix with stale/*.

2024-06-07 09:58 UTC, alexsuter commented
I'll close the PR and prefix the branch with stale/*. So that there are no builds running on our Jenkins server.

If you want to continue the work you can create a PR out of the stale/* branch.

The demo-projects is a special Axon Ivy Market artifact which can only be successfully built on our Jenkins server (because of test infrastructure which is only available in our internal network). For each branch builds are running unless they are prefix with stale/*.

2024-06-07 09:58 UTC, closed without merging